---
- name: Install httpd on AWS EC2 instances
  hosts: ec2_instances
  connection: aws_ssm
  become: true
  gather_facts: false
  vars:
    ansible_aws_ssm_bucket_name: ansible-tmp-654654150928-eu-north-1
    ansible_aws_ssm_region: eu-north-1
    ansible_aws_ssm_profile: learning
  tasks:
    - name: Wait for connection
      wait_for_connection:

    - name: Install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: present
      register: result

    - name: Check installation result
      debug:
        var: result